import { ContractOverride, buildTrace } from '../domain/contracts/types';
import { buildContractDoctrineBundle } from '../domain/doctrine';
import { DeepAnalysis, NarrativeCluster, NormalizedArticle, RuleTrace } from '../domain/entities';
import { ReasonerMode } from '../domain/enums';
import { DeepAnalysisSchema } from '../schemas/output';
import {
  LiveReasoningProvider,
  MarketIntelligenceReasoner,
  ReasonerSelectionMode,
  createDefaultReasoner
} from './reasoner';
import { ScreenedArticle } from './screen';

type AnalyzeOptions = {
  reasonerSelection?: ReasonerSelectionMode;
  reasoner?: MarketIntelligenceReasoner;
  liveProvider?: LiveReasoningProvider | null;
};

export type AnalyzeProviderStatus = 'simulated' | 'live_provider' | 'failed_provider_path';

export type AnalyzeResult = {
  analysis: DeepAnalysis | null;
  issue?: string;
  trace: RuleTrace[];
  providerStatus: AnalyzeProviderStatus;
  providerId: string;
};

const buildFailureResult = (
  override: ContractOverride,
  providerId: string,
  issue: string
): AnalyzeResult => ({
  analysis: null,
  issue,
  providerStatus: 'failed_provider_path',
  providerId,
  trace: [
    buildTrace(
      'analyze',
      override.ruleRefs.analysis,
      `Reasoning skipped because provider ${providerId} failed closed. ${issue}`,
      false
    )
  ]
});

export const runAnalyze = async (
  normalizedArticles: NormalizedArticle[],
  screenedArticles: ScreenedArticle[],
  override: ContractOverride,
  cluster: NarrativeCluster,
  options: AnalyzeOptions = {}
): Promise<AnalyzeResult> => {
  const doctrineBundle = buildContractDoctrineBundle(override.meta.id, override.source_files);
  const reasoner = options.reasoner ?? createDefaultReasoner(options.reasonerSelection, options.liveProvider);
  const invocation = await reasoner.generate({
    override,
    doctrineBundle,
    normalizedArticles,
    screenedArticles,
    cluster
  });

  if (!reasoner.configured) {
    return buildFailureResult(
      override,
      reasoner.providerId,
      invocation.issue ?? 'Reasoner provider is unavailable.'
    );
  }

  if (!invocation.analysis) {
    return buildFailureResult(
      override,
      reasoner.providerId,
      invocation.issue ?? `Provider ${reasoner.providerId} returned no reasoning payload.`
    );
  }

  const parsed = DeepAnalysisSchema.safeParse(invocation.analysis);
  if (!parsed.success) {
    const firstIssue = parsed.error.issues[0];
    const issueDetail = firstIssue
      ? `${firstIssue.path.join('.') || 'analysis'} ${firstIssue.message}`
      : 'schema validation failed.';

    return buildFailureResult(
      override,
      reasoner.providerId,
      `Provider ${reasoner.providerId} returned an invalid reasoning payload: ${issueDetail}`
    );
  }

  const analysis: DeepAnalysis = {
    ...parsed.data,
    reasoner_mode: reasoner.mode
  };

  const providerStatus: AnalyzeProviderStatus =
    reasoner.mode === ReasonerMode.SIMULATED_LLM ? 'simulated' : 'live_provider';

  return {
    analysis,
    providerStatus,
    providerId: reasoner.providerId,
    trace: [
      buildTrace(
        'analyze',
        override.ruleRefs.analysis,
        `Structured reasoning generated by ${reasoner.providerId} in ${analysis.reasoner_mode} mode with ${analysis.confirmed_facts.length} confirmed fact(s) and ${analysis.causal_chain.length} causal step(s).`,
        providerStatus === 'simulated'
      )
    ]
  };
};
